remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins

title: MESH-ON Lab.
logo: /assets/img/logo_small.png
description: Wireless device firmware development BLE/BLE-Mesh/WiFi/Z-Wave
show_downloads: false
